version: '1.0.{build}'
image: Visual Studio 2017
skip_branch_with_pr: true
branches:
  only:
  - dev
clone_depth: 1
init:
  # Good practise, because Windows
  - git config --global core.autocrlf true
before_build:
  # Resote backend solution
  - cmd: cd backend
  - cmd: dotnet restore --verbosity m
  # Resote DataAccumulator solution
  - cmd: cd ../DataAccumulator
  - cmd: dotnet restore --verbosity m
build_script:
  # output will be in ./DataAccumulator/DataAccumulator.WebAPI/bin/Release/netcoreapp2.1/publish/
  - cmd: dotnet publish -c Release
  # output will be in ./backend/Watcher/bin/Release/netcoreapp2.1/publish/
  - cmd: cd ../backend
  - cmd: dotnet publish -c Release
test_script:
 # tests in here
 # Temporarily disabling tests
 # - cmd: cd backend\Watcher.Tests
 # - cmd: dotnet xunit
artifacts:
 - path: '\backend\Watcher\bin\Release\netcoreapp2.1\publish'
   name: api

 - path: '\DataAccumulator\DataAccumulator.WebAPI\bin\Release\netcoreapp2.1\publish'
   name: dataaccumulator
notifications:
  - provider: Slack
    incoming_webhook:
      secure: om6ZaQPG70gvmoGaTQ2IfnTM8LQFROsCT1l23SGjLCVtLIufhCl+gDK1+K4UjfZNLmZJj/bjuNFuiVargaYtl64Ul4IslvGflpz7I6sSqc8=
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
    # on_build_status_changed: false
# Deploy backend solution
deploy:
  - provider: WebDeploy
    server:
      secure: GCqb1Ka4XlvY8MkxWTFIEKRyPyeJn63fFZmwQZGgGnpzsX/eBLKza5n+7SpMFw4mJ1MLj0/7DAYnYG9QQVafesY70PIr7SlFqlraT22KnGA=
    website:
      secure: cDbNO7KXt5Cq0UGJ+GkMLA==
    username:
      secure: J8/Xl8QbjGaOqjFDlyc54g==
    password:
      secure: hFkhEP/ZeDybHbIb1vAGKu2NZ52x/YymTxtJypk8CUjdkJlZHjpAKVyzuiKLp7ZoDLQDRFpFYvI/Z/VQyUmG2Q==
    remove_files: true
    app_offline: true
    artifact: api
# Deploy DataAccumulator
  - provider: WebDeploy
    server:
      secure: LnIWi29utYVomXWU0PG1AFecSPDJd/USEO4a4T86zexIwqk/aSVOHWAteyE/R9jIks5CUqKu9E4DthcBSp1f+YiSXPZpmCEv0aGMoGaH8K91YjIOXxc/BKY8o/L/ZvhK
    website:
      secure: hYlvucHSM2LSWT8vhwdbNC3kD0gcgF0irLQfDIxB2ZU=
    username:
      secure: /rzxhcd/9lH9CUiVczwWW2aV5iC1kEtmdtEUXfQ2ugo=
    password:
      secure: VkgvgECsj+SdjUoT5sYhacth/ab4Q0dRtRJQjL8pI78O61GhK474YqRauAmDopYqdV8weM61afpp2Rlg+/RIFg==
    remove_files: true
    app_offline: true
    artifact: dataaccumulator
