version: '1.0.{build}'
image: Visual Studio 2017
skip_branch_with_pr: true
branches:
  only:
  - dev
clone_depth: 1
init:
  # Good practise, because Windows
  - git config --global core.autocrlf true
before_build:
  # Display minimal restore text
  - cmd: cd backend
  - cmd: dotnet restore --verbosity m
build_script:
  # output will be in ./backend/Watcher/bin/Release/netcoreapp2.1/publish/
  - cmd: dotnet publish -c Release
test_script:
 # tests in here
 # Temporarily disabling tests
 # - cmd: cd backend\Watcher.Tests
 # - cmd: dotnet xunit
artifacts:
 - path: '\backend\Watcher\bin\Release\netcoreapp2.1\publish'
   name: api
deploy:
  - provider: WebDeploy
    server:
      secure: GCqb1Ka4XlvY8MkxWTFIEKRyPyeJn63fFZmwQZGgGnpzsX/eBLKza5n+7SpMFw4mJ1MLj0/7DAYnYG9QQVaferAktoWyR/lauzzwMw6byK8=
    website:
      secure: cDbNO7KXt5Cq0UGJ+GkMLA==
    username:
      secure: J8/Xl8QbjGaOqjFDlyc54g==
    password:
      secure: oKuycG/m6HKIsIk1D0gcFw+8Q+ChRVaEXSwvxEOQJl6C4ZsvfnfdmGJ/3TcUuu3bNZLk31eX10rFQd//JVybCQ==
    remove_files: true
    app_offline: true
    artifact: api